/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedVendasRouteImport } from './routes/_authenticated.vendas'
import { Route as AuthenticatedConferenciaRouteImport } from './routes/_authenticated.conferencia'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated.admin.users'
import { Route as AuthenticatedAdminExamesRouteImport } from './routes/_authenticated.admin.exames'
import { Route as AuthenticatedAdminAtendentesRouteImport } from './routes/_authenticated.admin.atendentes'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVendasRoute = AuthenticatedVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConferenciaRoute =
  AuthenticatedConferenciaRouteImport.update({
    id: '/conferencia',
    path: '/conferencia',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminExamesRoute =
  AuthenticatedAdminExamesRouteImport.update({
    id: '/admin/exames',
    path: '/admin/exames',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAtendentesRoute =
  AuthenticatedAdminAtendentesRouteImport.update({
    id: '/admin/atendentes',
    path: '/admin/atendentes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/conferencia': typeof AuthenticatedConferenciaRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/admin/atendentes': typeof AuthenticatedAdminAtendentesRoute
  '/admin/exames': typeof AuthenticatedAdminExamesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
}
export interface FileRoutesByTo {
  '/conferencia': typeof AuthenticatedConferenciaRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/atendentes': typeof AuthenticatedAdminAtendentesRoute
  '/admin/exames': typeof AuthenticatedAdminExamesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/conferencia': typeof AuthenticatedConferenciaRoute
  '/_authenticated/vendas': typeof AuthenticatedVendasRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/atendentes': typeof AuthenticatedAdminAtendentesRoute
  '/_authenticated/admin/exames': typeof AuthenticatedAdminExamesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conferencia'
    | '/vendas'
    | '/admin/atendentes'
    | '/admin/exames'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/conferencia'
    | '/vendas'
    | '/'
    | '/admin/atendentes'
    | '/admin/exames'
    | '/admin/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/conferencia'
    | '/_authenticated/vendas'
    | '/_authenticated/'
    | '/_authenticated/admin/atendentes'
    | '/_authenticated/admin/exames'
    | '/_authenticated/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vendas': {
      id: '/_authenticated/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AuthenticatedVendasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conferencia': {
      id: '/_authenticated/conferencia'
      path: '/conferencia'
      fullPath: '/conferencia'
      preLoaderRoute: typeof AuthenticatedConferenciaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/exames': {
      id: '/_authenticated/admin/exames'
      path: '/admin/exames'
      fullPath: '/admin/exames'
      preLoaderRoute: typeof AuthenticatedAdminExamesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/atendentes': {
      id: '/_authenticated/admin/atendentes'
      path: '/admin/atendentes'
      fullPath: '/admin/atendentes'
      preLoaderRoute: typeof AuthenticatedAdminAtendentesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedConferenciaRoute: typeof AuthenticatedConferenciaRoute
  AuthenticatedVendasRoute: typeof AuthenticatedVendasRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminAtendentesRoute: typeof AuthenticatedAdminAtendentesRoute
  AuthenticatedAdminExamesRoute: typeof AuthenticatedAdminExamesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedConferenciaRoute: AuthenticatedConferenciaRoute,
  AuthenticatedVendasRoute: AuthenticatedVendasRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminAtendentesRoute: AuthenticatedAdminAtendentesRoute,
  AuthenticatedAdminExamesRoute: AuthenticatedAdminExamesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
